



# Einführung {.unnumbered}

Diese Unterlagen begleiten den Digital Life Science Data Lab Kurs. Nils wird mit euch durch diese Beispiele in einem Workshop-Format arbeiten. Das bedeutet, er wird live programmieren und ihr werdet ihn begleiten. Wir möchten euch diese Codes bewusst *nicht* im Voraus geben, da das Schreiben eigener Codes und das Machen von Fehlern der beste Weg zum Lernen ist.



## Vorbereitung

Bitte stellt sicher, dass ihr euch für ein GoogleEarthEngine Account registriert habt. Siehe die Folien [hier](adls-lifescience-datalab-praktika.github.io/Register-GEE) für Anweisungen.


## Stundenplan


1. Lektion: 
   - Einführungs-Folien
   - @sec-js-console (Demo 1)
2. Lektion: 
   - @sec-js-demo-html (Demo 2)
   - @sec-js-task-basic-html (Task)
   - @sec-js-html-script (Demo 3)
   - @sec-js-task-years2days (Task)
   - @sec-js-methods (Demo 4)
3. Lektion
   - @sec-js-demo-website (Demo 5)
   - @sec-js-reverse-name (Task)
4. Lektion: 
   - @sec-gee-demo-unispec (Demo 1)
   - @sec-gee-task-unispec (Task)
   - @sec-gee-demo-multispec
5. Lektion: 
   - @sec-gee-demo-ndvi1 
   - @sec-gee-demo-ndvi2
   - @sec-gee-demo-forest



